"""Initial migration.

Revision ID: 6e1fc0979b8c
Revises: 
Create Date: 2023-10-04 16:50:01.750493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1fc0979b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_saved', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_tbl', schema=None) as batch_op:
        batch_op.drop_column('date_saved')

    # ### end Alembic commands ###
